---
deployment:
  tasks:
    #    - export DEPLOYPATH=/home/devrevostack/public_html/chilox-laravel
    - echo "Starting deployment..."

    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force >> /home/lilkuiah/pure_and_preloved/storage/logs/deploy.log
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan queue:restart

    - echo "Deployment finished"
